apiVersion: v1
kind: Service
metadata:
  name: python-docker-service2
spec:
  selector:
    app: python-docker
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-docker2
spec:
  selector:
    matchLabels:
      app: python-docker
  replicas: 5
  template:
    metadata:
      labels:
        app: python-docker
    spec:
      containers:
      - name: python-docker
        image: pruebadoker/python-docker
        imagePullPolicy: Never
        ports:
        - containerPort: 5000